steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - function-3
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=go121
  
options:
      logging: CLOUD_LOGGING_ONLY
