steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - function-2
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python39
  
options:
      logging: CLOUD_LOGGING_ONLY
