  steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/mindful-hall-431809-j6/cloud-run-source-deploy/quickstart-image', '.' ]
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/mindful-hall-431809-j6/cloud-run-source-deploy/quickstart-image']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'poc-cloud-build'
    - '--image'
    - 'us-central1-docker.pkg.dev/mindful-hall-431809-j6/cloud-run-source-deploy/quickstart-image'
    - '--region'
    - 'us-central1'
    
  images:
  - 'us-central1-docker.pkg.dev/mindful-hall-431809-j6/cloud-run-source-deploy/quickstart-image'

  options:
      logging: CLOUD_LOGGING_ONLY
