  steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/poc-cloud-build:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/poc-cloud-build:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'poc-cloud-build'
    - '--image'
    - 'gcr.io/$PROJECT_ID/poc-cloud-build:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    
  images:
  - 'gcr.io/$PROJECT_ID/poc-cloud-build:$COMMIT_SHA'

  - name: 'bash'
    args: ['echo', 'Hello world!']
  logsBucket: 'LOGS_BUCKET_LOCATION'
  serviceAccount: 'projects/mindful-hall-431809-j6/serviceAccounts/438724874462-compute@developer.gserviceaccount.com'
 
  options:
    logging: GCS_ONLY
  
options:
  logging: CLOUD_LOGGING_ONLY
