substitutions:
  _DOCKER_19: DOCKER_VERSION=5:19.03.153-0ubuntu-focal
  _DOCKER_20: DOCKER_VERSION=5:20.10.243-0ubuntu-focal
  _DOCKER_24: DOCKER_VERSION=5:24.0.9-1ubuntu.20.04focal

steps:
name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=temp'
  - '--file=Dockerfile-base'
  - '.'
  id: 'base'

# Build all supported versions.
name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/docker:19.03.15'
  - '--file=Dockerfile-versioned'
  - '--build-arg=${_DOCKER_19}'
  - '.'
  id: '19.03.15'
  wait_for: ['base']

name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/docker:latest'
  - '--tag=gcr.io/$PROJECT_ID/docker:20.10.24'
  - '--file=Dockerfile-versioned'
  - '--build-arg=${_DOCKER_20}'
  - '.'
  id: '20.10.24'
  wait_for: ['base']

name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/$PROJECT_ID/docker:24.0.9'
    - '--file=Dockerfile-versioned'
    - '--build-arg=${_DOCKER_24}'
    - '.'
  id: '24.0.9'
  wait_for: [ 'base' ]


# Test each version by using it to run "docker build" on itself.
name: 'gcr.io/$PROJECT_ID/docker:19.03.15'
  args:
  - 'build'
  - '--file=Dockerfile-versioned'
  - '--build-arg=${_DOCKER_19}'
  - '.'
  wait_for: ['19.03.15']

name: 'gcr.io/$PROJECT_ID/docker:20.10.24'
  args:
  - 'build'
  - '--file=Dockerfile-versioned'
  - '--build-arg=${_DOCKER_20}'
  - '.'
  wait_for: ['20.10.24']

name: 'gcr.io/$PROJECT_ID/docker:24.0.9'
  args:
    - 'build'
    - '--file=Dockerfile-versioned'
    - '--build-arg=${_DOCKER_24}'
    - '.'
  wait_for: ['24.0.9']


# Here are some things that can be done with this builder:

# Get info about an image. This effectively runs the "docker inspect" command on
# the image built above.
name: 'gcr.io/$PROJECT_ID/docker'
  args: ['inspect', 'gcr.io/$PROJECT_ID/docker']
  wait_for: ['20.10.24']
# Execute a container. The "busybox" container is executed within the docker
# build step to echo "poc success!"
name: 'gcr.io/$PROJECT_ID/docker'
  args: ['run', 'busybox', 'echo', 'poc success!']
  wait_for: ['20.10.24']

images:
'gcr.io/$PROJECT_ID/docker:latest'
'gcr.io/$PROJECT_ID/docker:19.03.15'
'gcr.io/$PROJECT_ID/docker:20.10.24'
'gcr.io/$PROJECT_ID/docker:24.0.9'

options:
  logging: CLOUD_LOGGING_ONLY
  
timeout: 1200s
