steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - function-2
  - --source=.
  --runtime python39
  - --trigger-bucket 
  - homepage
  
options:
      logging: CLOUD_LOGGING_ONLY
